spring.application.name=backend

# Configuración de conexión a Supabase (Cambiado al puerto 6543 del Transaction Pooler)
spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.qnzbrdnujtfysngmtlqf
spring.datasource.password=DripShoes7770

# Control de Conexiones (Evita que vuelva a superar el límite de 15)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect